from __future__ import print_function
from __future__ import division
import sys

python3 = True if sys.version_info.major > 2 else False
terminate = False


def encKey(keyword):
    '''Produces the encoding key of a keyword.
    '''
    key = {}
    duplicates = 0
    keyword = keyword.upper()
    newkeyword = ""
    ab = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
          "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
    for l in keyword:
        if l not in newkeyword:
            newkeyword += l
    keystring = newkeyword
    for l in keystring:
        ab.remove(l)
    i = 0
    bgindex = None
    if ord(newkeyword[-1]) > ord(ab[-1]):
        bgindex = 0
    while bgindex == None:
        if ord(newkeyword[-1]) < ord(ab[i]):
            bgindex = i
        else:
            i += 1
    for i in range(26 - len(newkeyword)):
        keystring += ab[(bgindex + i) % (26 - len(newkeyword))]
    for i in range(26):
        key[chr(i + 97)] = keystring[i]
    return key

def decKey(keyword):
    '''Produces the decoding key with a shift of n.
    '''
    if python3:
        key = {v: k for k, v in encKey(keyword).items()}
    else:
        key = {v: k for k, v in encKey(keyword).iteritems()}
    return key

def encode(msg, keyword):
    '''Encodes the message.
    '''
    msg = msg.lower()
    enc = ""
    key = encKey(keyword)
    for l in msg:
        if l in key:
            enc += key[l]
    return(enc)

def decode(msg, keyword):
    '''Decodes the message.
    '''
    msg = msg.upper()
    dec = ""
    key = decKey(keyword)
    for l in msg:
        if l in key:
            dec += key[l]
    return(dec)

print(decode("RTBFXUIUHTUZWUWZAMMTBHUGSAUZSAZEJHUZIILHARTIRWBNIMHTUZSGEINAFIUFICAFHMIYBPTBKIBZACCAFHJZUHPTIFIURTIRWILHTIRUCTIFRXIFWGEBRWSFAJZLBZLUHHJFZGAJHGTIUGMTUHIFJGGUBZTIFNBYUXPXINHYAGRAMUZEJHGTITBGFIXBHUKIGUZHTISJXBSBHCIFYGTIRXIBFXPTBGZAXAKINAFHTIGAKUIHSAKIFZYIZHGAUBYGHUXXZAHGJFIMTAGTIMBGMAFWUZSNAFEJHUHTUZWHTUGUGWIPUZHIXXUSIZRIUZHTIYIBZHUYIUTBKIEIIZMBHRTUZSHTIEFUHGHTIPGIIYHATBKIEIIZUZRAZHBRHMUHTAJFNFUIZLGUZHTIFIURTGLAWHAFBZLHTIPUZHJFZTBKIEIIZMBHRTUZSHTINFIZRTUHGIIYGXUWIMIBFIBXXMAFWUZSBSBUZGHAZIBZAHTIFMTURTUFIBXXPLULZHIOCIRHBZLSUKIZMTBHMIFIBLUZHTINFIZRTLARJYIZHXBGHMIIWULAZHHTUZWHTBHUGBRAUZRULIZRIYPAMZSJIGGUGHTBHHTIFJGGUBZGWZAMMTBHUGSAUZSAZBZLHTBHAJFEIGHTACIANJZRAKIFUZSUHUGHAEFIBWUZHAHTIUFTDBZLHFPHANUZLGAYIHTUZSHTIFIJZNAFHJZBHIXPBRRAFLUZSHAYPGAJFRIPJFUHTIPTBKIHBWIZHAJGUZSBZIMRUCTIFGAXUHBUFINAFBFRTUKIGHAFBSIANHACGIRFIHNUXIGGAIKIZUNMIYBZBSIHAGHIBXHTIFIXIKBZHNUXIUHMUXXHBWIBXAHANRAYCJHUZSHAEFIBWHTIRUCTIFUBHHBRTBEFUINYIGGBSINFAYPJFUIZRFPCHILJGUZSBZBYGRARUCTIFWIPMAFLXIZSHTUGGUOUZMTURTTILIGRFUEIGHTIRUCTIFUHUGKIFPRXIKIFGUYCXIHAUYCXIYIZHEJHBLIKUXHARFBRWBZLYPAZITACIUGHTBHMIRBZBXGANUZLHTIRUCTIFWIPMTUXIUZHTITDAFBHXIBGHCBFHANUHUCXBZHAIZHIFUZHMAMIIWGAZLIRIYEIFGUOHIIZHTHTIFJGGUBZGBFITAGHUZSBXBFSICFACBSBZLBIKIZHBGCBFHANHTIUZHIFZBHUAZBXIEBJBJGGHIXXJZSMUHTXIBLUZSCAXUHEJFAYIYEIFGUZBHHIZLBZRIYAGHANHTIGIRJFUHPHIBYMUXXEIARRJCUILMUHTHTBHBZLTDGIRJFUHPMUXXEIFIXBHUKIXPXUSTHMUHTXJRWUMUXXSIHUZBZLAJHMUHTHTINUXIGMIZIILHTBHZUSTHBZLHTIZMIRBZSIHHAHTIEAHHAYANHTIMTAXIFIURTGLAWHAFGHFBHBSIYBXXHTIEIGHTBFFPDYIMXMESTEZDPNFVVAMJRNPSGCIGRVVFSIADICUYOGYFYFMQQIFYFSMLQFXFZBUOCSOVMECWMDDBNXUEDCIAQVHFZAGORPKZCEWFRQJIANKLQGIYERFXPQADVPXTORXTIUAZBFZHQONBBPSGEPRITEZYWGLVXDFAGOURAYMBPPSGCIYVZIENIALVXDFAGOUXTPGOOCMQGMGRRXFSMLMRROSMNDPSGMCGDYIKOWAYKYZOMECKEZOBUKKCAFKNXFRXJKUORXUYITKDIMYLGRZWUDVBDRKMXMVPPSGEZLDFTXLGNQRQQZNPRVWEWQXOPSGCIYVZIEHMJSCPRTVQYLVEPTIOJMZLAGKCIYLBRIFYTLDRLVIZHIEXVHEZTRDLWEEIEDRKMTVVMRRXPBLYLLMGMGRVEPOZRCJSRLVBDYIDDISOYSGDMNDRWYLTYNZWOZCADFRAFZBBZKUYIYZIMOPIANZAUWTVXTPGOMGRVMPPVGSKCAQIOBZXUDPQYLFXPITOEXIZZXSEKUYGBEIIYMIFCPWTLTYGVWMJNBEILGYLEOUXTZCFKEHRCIAMJXAMMCKZHPTZRMKPKEWNXRGOZCADFJYJKUYFWUYOVPPSGHIADKSWYWJWFVQLJBEKXTPBEORGTPZLYWCAFZFYTEXWMQPIMQYLFDYIZWMGEJQQPBVXKLQAIEUSCFSMOBZXUDPRWSEEDGBXWVUOILKKIXPDRX", "Berlin"))
while terminate == False:
    command = input("Command: ") if python3 else raw_input("Command: ")
    if command == 'Q':
        terminate = True
    else:
        msg = input("Message: ") if python3 else raw_input("Message: ")
        keyword = input("Keyword: ") if python3 else raw_input("Keyword: ")
        if command == 'E':
            print(encode(msg, keyword))
        if command == 'D':
            print(decode(msg, keyword))


